// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgD0O8mm2A0nvqQ_Q8oyEgpBE2jAJt1kY',
    appId: '1:648290875853:web:47000585e270124b7eac84',
    messagingSenderId: '648290875853',
    projectId: 'jarnama-e9826',
    authDomain: 'jarnama-e9826.firebaseapp.com',
    storageBucket: 'jarnama-e9826.appspot.com',
    measurementId: 'G-GYTNT9V010',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp_XFKTTVVlxbYnDIkK57hdFrgaLHZhhg',
    appId: '1:648290875853:android:9f6a581f23b5a2917eac84',
    messagingSenderId: '648290875853',
    projectId: 'jarnama-e9826',
    storageBucket: 'jarnama-e9826.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOQqQzuJeWacgfgSCQJLWlJ-RR12dKHy4',
    appId: '1:648290875853:ios:a5a34181a2d3e5d27eac84',
    messagingSenderId: '648290875853',
    projectId: 'jarnama-e9826',
    storageBucket: 'jarnama-e9826.appspot.com',
    iosClientId: '648290875853-g1rvhvcu76hl85nldq34tuqufd0lle1c.apps.googleusercontent.com',
    iosBundleId: 'com.example.jarnamaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOQqQzuJeWacgfgSCQJLWlJ-RR12dKHy4',
    appId: '1:648290875853:ios:a5a34181a2d3e5d27eac84',
    messagingSenderId: '648290875853',
    projectId: 'jarnama-e9826',
    storageBucket: 'jarnama-e9826.appspot.com',
    iosClientId: '648290875853-g1rvhvcu76hl85nldq34tuqufd0lle1c.apps.googleusercontent.com',
    iosBundleId: 'com.example.jarnamaApp',
  );
}
